# Generated by Django 3.1.1 on 2020-09-26 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='Address',
            new_name='ngo_Address',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='ngo_email',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='ngo_name',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='ngo_pass',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='ngo_phone',
        ),
        migrations.AddField(
            model_name='ngo',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('Address', models.TextField(max_length=300)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='donations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.donar'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
