# Generated by Django 3.0.8 on 2020-09-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200927_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='donations',
            name='ngo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.NGO'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='ngo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.NGO'),
        ),
    ]
